services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: weekly-report-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: weekly_report_system
      MYSQL_USER: weekly_report_user
      MYSQL_PASSWORD: weekly_report_pass
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - weekly-report-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Spring Boot Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: weekly-report-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: weekly_report_system
      DB_USERNAME: root
      DB_PASSWORD: rootpass123
      JWT_SECRET: MyVerySecureWeeklyReportJwtSigningKeyForHS512AlgorithmMustBe512BitsOrGreater2024!@#$%^&*()_+=
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - weekly-report-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    volumes:
      - ./logs:/app/logs

  # Frontend Vue.js Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: weekly-report-frontend
    environment:
      NODE_ENV: production
      BACKEND_URL: http://23.95.193.155:8082
    ports:
      - "3003:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - weekly-report-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:
    driver: local

networks:
  weekly-report-network:
    driver: bridge