version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: weekly-report-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: weekly_report
      MYSQL_USER: weekly_report
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - weekly-report-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Spring Boot Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: weekly-report-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: weekly_report
      DB_USERNAME: weekly_report
      DB_PASSWORD: password
      JWT_SECRET: mySecretKeyForProduction
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - weekly-report-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - ./logs:/app/logs

  # Frontend (placeholder for when frontend is added)
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   container_name: weekly-report-frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   networks:
  #     - weekly-report-network

volumes:
  mysql_data:
    driver: local

networks:
  weekly-report-network:
    driver: bridge