# Production Environment Configuration

environment: production

# Database Configuration
database:
  host: ${DB_HOST}
  port: 3306
  name: ${DB_NAME:-weekly_report_prod}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  max_connections: 50
  connection_timeout: 10s
  ssl_mode: require

# Redis Configuration
redis:
  host: ${REDIS_HOST}
  port: 6379
  database: 0
  password: ${REDIS_PASSWORD}
  timeout: 3s
  ssl_enabled: true

# Application Configuration
app:
  name: "Weekly Report System"
  version: "1.0.0"
  port: 8080
  debug: false
  log_level: WARN
  cors_origins:
    - "https://weekly-report.example.com"
  jwt_secret: ${JWT_SECRET}
  jwt_expiration: 7200 # 2 hours

# Frontend Configuration
frontend:
  url: "https://weekly-report.example.com"
  api_base_url: "https://api.weekly-report.example.com"

# Email Configuration
email:
  smtp_host: ${SMTP_HOST}
  smtp_port: 587
  smtp_user: ${SMTP_USER}
  smtp_password: ${SMTP_PASSWORD}
  from_email: "noreply@weekly-report.example.com"
  from_name: "Weekly Report System"
  use_tls: true

# File Storage Configuration
storage:
  type: "s3" # Use S3 for production
  s3_bucket: ${S3_BUCKET_NAME}
  s3_region: ${S3_REGION:-us-west-2}
  s3_access_key: ${S3_ACCESS_KEY}
  s3_secret_key: ${S3_SECRET_KEY}
  max_file_size: 50MB
  allowed_extensions:
    - "pdf"
    - "doc"
    - "docx"
    - "xls"
    - "xlsx"
    - "png"
    - "jpg"
    - "jpeg"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30s
  log_aggregation: true

# External API Configuration
external_apis:
  enable_mock: false
  timeout: 10s
  rate_limiting: true
  max_requests_per_minute: 60

# Security Configuration
security:
  password_min_length: 12
  password_require_special: true
  password_require_numbers: true
  password_require_uppercase: true
  max_login_attempts: 3
  lockout_duration: 60m
  session_timeout: 4h
  enable_2fa: true
  https_only: true
  secure_cookies: true

# Feature Flags
features:
  enable_registration: true
  enable_password_reset: true
  enable_email_notifications: true
  enable_audit_logging: true
  enable_data_export: true
  enable_analytics: true

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *" # Daily at 2 AM
  retention_days: 30
  s3_backup_bucket: ${S3_BACKUP_BUCKET}

# Performance Configuration
performance:
  connection_pool_size: 20
  query_timeout: 30s
  cache_ttl: 3600 # 1 hour
  enable_compression: true
  static_file_cache_duration: 86400 # 24 hours