# 生产环境配置
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 120000
      pool-name: WeeklyReportHikariCP-Prod
      connection-test-query: SELECT 1
      validation-timeout: 10000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 4096
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # 生产环境严格验证，绝不修改schema
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        connection:
          provider_disables_autocommit: false

  # Redis配置 - 生产环境（必须通过环境变量配置）
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:5000}
      # 生产环境连接池配置
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 3000

# 生产环境最少日志
logging:
  level:
    com.weeklyreport: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
    com.zaxxer.hikari: WARN
    root: WARN

# AI配置 - 生产环境使用DeepSeek
ai:
  default-provider: deepseek
  enable-fallback: true
  max-retries: 2
  deepseek:
    enabled: true
  openai:
    enabled: false
