# Docker容器环境配置
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:weekly_report_system}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpass123}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
      leak-detection-threshold: 60000
      pool-name: WeeklyReportHikariCP-Docker
      connection-test-query: SELECT 1
      validation-timeout: 5000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false

  # Redis配置 - Docker容器环境
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:3000}

# Docker环境日志
logging:
  level:
    com.weeklyreport: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    com.zaxxer.hikari: WARN
    root: INFO

# AI配置 - Docker环境使用DeepSeek
ai:
  default-provider: deepseek
  enable-fallback: true
  max-retries: 2
  deepseek:
    enabled: true
  openai:
    enabled: false
