# 测试服务器环境配置
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:23.95.193.155}:${DB_PORT:3309}/${DB_NAME:weekly_report_system}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpass123}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
      leak-detection-threshold: 60000
      pool-name: WeeklyReportHikariCP-Test
      connection-test-query: SELECT 1
      validation-timeout: 8000
      auto-commit: false

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # 测试环境验证schema
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        generate_statistics: false

  # Redis配置 - 测试服务器环境
  data:
    redis:
      host: ${REDIS_HOST:23.95.193.155}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:1}
      timeout: ${REDIS_TIMEOUT:3000}

# 测试环境适度日志
logging:
  level:
    com.weeklyreport: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
    com.zaxxer.hikari: WARN
    root: INFO

# AI配置 - 测试环境使用DeepSeek
ai:
  default-provider: deepseek
  deepseek:
    enabled: true
  openai:
    enabled: false
